name: Ejecutar Bot Diario
on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 PM UTC (8:00 AM CDMX)
  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar bot
        run: python main.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}