name: Ejecutar Bot Financiero
on:
  schedule:
    - cron: '0 12 * * 1-5'  # Lunes a Viernes a las 12:00 PM UTC
  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install yfinance --upgrade
          
      - name: Ejecutar bot con reintentos
        run: |
          for i in {1..3}; do
            python main.py && break || sleep 30
          done
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}